# Generated by Django 4.2.7 on 2023-11-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Раздел')),
                ('image', models.ImageField(blank=True, null=True, upload_to='selfedu/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Материал')),
                ('image', models.ImageField(blank=True, null=True, upload_to='selfedu/', verbose_name='Фото')),
                ('video', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfedu.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('hint', models.TextField(verbose_name='Подсказка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfedu.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Тестовый вопрос',
                'verbose_name_plural': 'Тестовые вопросы',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Вариант ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfedu.testquestion', verbose_name='Тестовый вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
