# Generated by Django 4.2.7 on 2023-11-25 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfedu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Отвечен')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfedu.testquestion', verbose_name='Тестовый вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
