# Generated by Django 4.2.7 on 2023-11-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfedu', '0002_usertestcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
    ]
